#!/bin/bash

#PBS -l walltime=200:00:00
#PBS -l nodes=1:ppn=8
#PBS -l vmem=120gb
#PBS -M tyler.peirce@my.jcu.edu.au
#PBS -m abe
#PBS -N normalisation
#PBS -S /bin/bash
cd $PBS_O_WORKDIR

. configfile.txt

#mkdir $PWD/02_input
#mkdir $PWD/02_results_trinity

#module load java
#module load trinity
#cp $PREP/R1p_suf1_R1 $PREP/R2p_suf2_R2 $PWD/02_input
#Trinity --no_version_check --normalize_reads --seqType fq --max_memory 100G --CPU 8 --left $PREP/R1p_suf1_R1 --right $PREP/R2p_suf2_R2 --output $ASSM

#module load bioperl

#perl $SCRIPTS/seq_stats.pl $ASSM/Trinity.fasta >$COUNTS/02_seq_stats_assm

module load bioperl
module load bbmap
module load java

##remove sequences smaller than 400bp

#perl $SCRIPTS/removesmalls.pl 400 $ASSM/Trinity.fasta > $ASSM/02_Trinity-l400.fasta


##run stats on the sequences with the <400bp sequences removed

#perl $SCRIPTS/seq_stats.pl $ASSM/02_Trinity-l400.fasta >>$COUNTS/02_seq_stats_assm_removesmall


##run the GC content stats on the sequences

sh $PWD/bbmap/stats.sh in=$DATADIR/02_Trinity-l400.fasta > $COUNTS/02_GC_bbmap_Trinisty-l400


