#!/bin/bash

#PBS -l walltime=20:00:00
#PBS -l nodes=1:ppn=2
#PBS -l vmem=150gb
#PBS -M tyler.peirce@my.jcu.edu.au
#PBS -m abe
#PBS -N uniprot
#PBS -S /bin/bash
cd $PBS_O_WORKDIR

. configfile.txt

mkdir $PWD/03_input
mkdir $PWD/03_results
module load blast+
#cp $ASSM/02_Trinity-l400.fasta

wget ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz
wget ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/idmapping/idmapping_selected.tab.gz


gunzip uniprot_sprot.fasta.gz 
gunzip idmapping_selected.tab.gz
 
module load blast+
makeblastdb -in uniprot_sprot.fasta -dbtype prot
