#!/bin/bash

. $PWD/configfile.txt
###copy the output from 13_KEG to your laptop

####use web browser to submit transcriptome_4kegg.fasta file to KEGG's KAAS server 
####( http://www.genome.jp/kegg/kaas/ )

####select SBH algorithm
####upload nucleotide query (transcriptome_4kegg.fasta)
####select representative genes for model inverts 
#### copy this into the representetive genes for inverts: dme, cel, nve, hmg, aqu, cin
####(Drosophila, C.elegans, N.vec, Hydra, A.queenslandica, Ascidian)

##### Once it is done, download the 'text' output from KAAS, name it query.ko (default)
### then run the script below

RESULTS=$PWD/13_results

#non missing annotations
cat $RESULTS/query.ko | awk '{if ($2!="") print }' > $RESULTS/iso2kegg.tab

rm $RESULTS/iso2kegg.unique.ann.tab
echo 'unique annotations' >>$RESULTS/iso2kegg.unique.ann.tab
cat iso2kegg.tab | cut -f 2 | sort -u | wc -l >>$RESULTS/iso2kegg.unique.ann.tab

echo 'total non missing annotations' >>$RESULTS/iso2kegg.unique.ann.tab 
cat iso2kegg.tab | wc -l >> $RESULTS/iso2kegg.unique.ann.tab
