#!/bin/bash
#PBS -l walltime=100:00:00
#PBS -l nodes=1:ppn=1
#PBS -l vmem=20gb
#PBS -M tyler.peirce@my.jcu.edu.au
#PBS -m abe
#PBS -N kog
#PBS -S /bin/bash
cd $PBS_O_WORKDIR

. configfile.txt
module load blast+

mkdir $PWD/09_results

RESULTS=$PWD/09_results


#wget http://korflab.ucdavis.edu/Datasets/genome_completeness/core/248.prots.fa.gz
mv 248.prots.fa.gz $RESULTS
gunzip $RESULTS/248.prots.fa.gz


cp $AN_QUERY $RESULTS 
makeblastdb -in $RESULTS/04_ALL_iso_corrected.fasta  -dbtype nucl


OUTPUT=$RESULTS/09_248.brtab
tblastn -query $RESULTS/248.prots.fa -db $RESULTS/04_ALL_iso_corrected.fasta -evalue 1e-10 -outfmt "6 qseqid sseqid evalue bitscore qcovs" -max_target_seqs 1 -num_threads 16 >$OUTPUT



#calculate percentage of represented KOGS

cat $OUTPUT | perl -pe 's/.+(KOG\d+)\s.+/$1/' | sort -u | wc -l | awk '{print $1/248}' >$OUTPUT.percentKOG
