#!/bin/bash

#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=4
#PBS -l vmem=20gb
#PBS -M tyler.peirce@my.jcu.edu.au
#PBS -m abe
#PBS -N mapping
cd $PBS_O_WORKDIR

. configfile.txt

##setting up files for mapping

mkdir $PWD/21_results
RESULTS=$PWD/20_results

cp $PWD/04_results/04_ALL_iso_corrected.fasta $RESULTS/transcriptome.fasta


###building transcriptome
module load bowtie2
module load bioperl

bowtie2-build $RESULTS/transcriptome.fasta $RESULTS/transcriptome.fasta

cd $RESULTS
perl $SCRIPTS/iRNAseq_bowtie2map.pl "trim$" $RESULT/transcriptome.fasta > $RESULTS/21_maps.job


module load bowtie2

for SAMPLE in $RESULTS/*.fastq; do

bowtie2 --local -x $RESULTS/transcriptome.fasta -U $SAMPLE -S $SAMPLE.sam --no-hd --no-sq --no-unal -k 5

done

cd ..
mv $RESULTS/*.sam $PWD/21_results
