#!/bin/bash

#PBS -l nodes=1:ppn=2
#PBS -l walltime=24:0:0
#PBS -M tyler.peirce@my.jcu.edu.au
#PBS -m abe
#PBS -N sc.job
cd $PBS_O_WORKDIR

. configfile.txt

module load bowtie2
cp $PWD/04_results/04_seq2iso.tab $PWD/21_results
SAMDIR=$PWD/21_results
TRANS=$SAMDIR/04_seq2iso.tab

for SAM in $SAMDIR/*.sam; do
 	$SCRIPTS/samcount.pl $SAM $TRANS aligner=bowtie2 >$SAM.counts
done

mkdir $PWD/22_results
RESULTS=$PWD/22_results
mv $SAMDIR/*.counts $RESULTS


$SCRIPTS/expression_compiler.pl $RESULTS/*.sam.counts > $RESULTS/allcounts.txt


cat $RESULTS/allcounts.txt | sed -r 's/_[GATC]{6}.fastq.trim.sam.counts//g' > $RESULTS/allcountsTankExpt.txt

cat $RESULTS/allcounts.txt | sed -r 's/.fastq.trim.sam.counts//g' > $RESULTS/allcountsSSCExpt.txt

